version: '3.8'

services:
  # SERVICE DE BASE DE DONNÉES (MySQL)
  db:
    # Utilise le Dockerfile que nous venons de créer
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    # Définit les variables pour la création de la base de données au démarrage
    environment:
      # ATTENTION : Utilisez toujours ces variables de Render, ne mettez JAMAIS de mot de passe ici !
      # Nous allons les définir dans le tableau de bord Render, elles seront lues par le conteneur.
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      # Volume pour persister les données de la base
      - db_data:/var/lib/mysql

  # SERVICE WEB (Votre application PHP/Apache)
  app:
    # Utilise votre Dockerfile PHP existant
    build:
      context: .
      dockerfile: Dockerfile
    # Le conteneur dépend du démarrage réussi de la base de données
    depends_on:
      - db
    ports:
      # Expose le port 80 du conteneur vers le port 80 de la machine hôte
      - "80:80"
    environment:
      # Injecte l'URL de la base de données dans le conteneur PHP
      # L'hôte DB_HOST devient 'db', le nom du service dans Docker Compose.
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}

      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_DEBUG: ${APP_DEBUG}

# Définit le volume persistant pour la base de données
volumes:
  db_data:



